stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE: vindzory/python-mysql-app

build:
  stage: build
  script:
    - docker build -t $DOCKER_IMAGE .
    - docker push $DOCKER_IMAGE

deploy:
  stage: deploy
  script:
    - kubectl apply -f k8s/mysql-deployment.yaml
    - kubectl apply -f k8s/python-app-deployment.yaml
    - kubectl apply -f k8s/service.yaml
  only:
    - main