apiVersion: apps/v1
kind: Deployment
metadata:
  name: random-string-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: random-string
  template:
    metadata:
      labels:
        app: random-string
    spec:
      containers:
        - name: random-string-app
          image: vindzory/random-string-app:latest
          ports:
            - containerPort: 5000